export * as govnImCore from "https://denopkg.com/gov-suite/governed-im@v0.7.1/core/mod.ts";
export * as artfPersist from "https://denopkg.com/shah/artifacts-persistence@v1.2.0/mod.ts";
export * as contextMgr from "https://denopkg.com/shah/context-manager@v1.0.7/mod.ts";
export * as specModule from "https://denopkg.com/shah/specification-module@v1.0.9/mod.ts";
export * as textInflect from "https://denopkg.com/shah/text-inflect@v1.0.5/mod.ts";
export * as textInterpolate from "https://denopkg.com/shah/text-interpolate@v1.0.8/mod.ts";
export * as textWhitespace from "https://denopkg.com/shah/text-whitespace@v1.0.4/mod.ts";
export * as safety from "https://denopkg.com/shah/ts-safety@v0.3.1/mod.ts";
export * as valueMgr from "https://denopkg.com/shah/value-manager@v1.0.10/mod.ts";
